// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVftw93MC0uIjav3l9iK498gcIYS0mbTI',
    appId: '1:1042032759528:web:a26c335ff36f859ca4af5d',
    messagingSenderId: '1042032759528',
    projectId: 'batch-meal-v2',
    authDomain: 'batch-meal-v2.firebaseapp.com',
    storageBucket: 'batch-meal-v2.firebasestorage.app',
    measurementId: 'G-6YD29G9FR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKi7ApXRZYN_KaRyaNosYEiFVElETFiPY',
    appId: '1:1042032759528:android:df9fe9b6087c2d13a4af5d',
    messagingSenderId: '1042032759528',
    projectId: 'batch-meal-v2',
    storageBucket: 'batch-meal-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOMTj903JeR582JOiELo8GAtQb0h0rAOg',
    appId: '1:1042032759528:ios:028e0859e9c45411a4af5d',
    messagingSenderId: '1042032759528',
    projectId: 'batch-meal-v2',
    storageBucket: 'batch-meal-v2.firebasestorage.app',
    iosBundleId: 'com.example.batchMealV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOMTj903JeR582JOiELo8GAtQb0h0rAOg',
    appId: '1:1042032759528:ios:028e0859e9c45411a4af5d',
    messagingSenderId: '1042032759528',
    projectId: 'batch-meal-v2',
    storageBucket: 'batch-meal-v2.firebasestorage.app',
    iosBundleId: 'com.example.batchMealV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVftw93MC0uIjav3l9iK498gcIYS0mbTI',
    appId: '1:1042032759528:web:624f447adf05958ba4af5d',
    messagingSenderId: '1042032759528',
    projectId: 'batch-meal-v2',
    authDomain: 'batch-meal-v2.firebaseapp.com',
    storageBucket: 'batch-meal-v2.firebasestorage.app',
    measurementId: 'G-S9Y3YLEN4F',
  );
}
